import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, CloudRain, Snowflake, ThermometerSun, Wind } from "lucide-react";
import { DataFreshness, DataTypeBadge, DataUnavailable, SourceBadge } from "@/components/climate/source-ui";
import { formatClimateDate, formatProbability, formatSigned, humanize } from "@/lib/climate-format";
import type { ClimateCO2, ClimateENSO, ClimateOutlook, ClimateOverview, EarthEvent, EarthEvents } from "@/types/climate";
import { SeriesPlot } from "./series-plot";

type HomeClimateData = { overview: ClimateOverview | null; co2: ClimateCO2 | null; enso: ClimateENSO | null; outlook: ClimateOutlook | null; events: EarthEvents | null };
function HeroSignal({ label, value, detail, type }: { label: string; value: string; detail: string; type: "estimate" | "analysis" | "forecast" }) { return <li><div><span>{label}</span><DataTypeBadge type={type} /></div><strong>{value}</strong><small>{detail}</small></li>; }
function coordinateLabel(coordinates: unknown[] | undefined) { const point = coordinates && (Array.isArray(coordinates[0]) ? coordinates[0] : coordinates); return point && typeof point[0] === "number" && typeof point[1] === "number" ? `${point[1].toFixed(2)}°, ${point[0].toFixed(2)}°` : "Geometry supplied by NASA EONET"; }
function EventCard({ event }: { event: EarthEvent }) { const href = event.sources[0]?.url ?? event.eonet_url; return <li data-home-event-card><span className="home-event-dot" aria-hidden="true" /><div><small>{event.categories[0]?.title ?? "Earth event"}</small><strong>{event.title}</strong><p>{coordinateLabel(event.latest_geometry?.coordinates)}</p>{event.latest_geometry?.date ? <time dateTime={event.latest_geometry.date}>{formatClimateDate(event.latest_geometry.date)}</time> : null}{href ? <a href={href} target="_blank" rel="noreferrer">View source <ArrowUpRight size={12} aria-hidden="true" /></a> : null}</div></li>; }
function eventPoint(event: EarthEvent) { const coordinates = event.latest_geometry?.coordinates; const point = coordinates && (Array.isArray(coordinates[0]) ? coordinates[0] : coordinates); return point && typeof point[0] === "number" && typeof point[1] === "number" ? { x: ((point[0] + 180) / 360) * 100, y: ((90 - point[1]) / 180) * 100 } : null; }

export function HomeDataStory({ overview, co2, enso, outlook, events }: HomeClimateData) {
  const temperature = overview?.global_temperature ?? null;
  const currentCO2 = co2?.latest;
  const currentNino = enso?.observations.latest_nino34;
  return <>
    <section className="home-hero" aria-labelledby="home-title"><div className="home-shell home-hero-grid"><div className="home-hero-copy home-reveal"><p className="home-kicker">Earth observatory · source-backed climate intelligence</p><h1 id="home-title">The planet is always <em>sending signals.</em></h1><p className="home-hero-deck">Read what the atmosphere, ocean, ice, and Pacific are showing now—then choose where your own climate pathway begins.</p><div className="home-hero-actions"><a href="#signals">Read the briefing <ArrowDown size={16} aria-hidden="true" /></a><Link href="/climate-now">Explore Climate Now <ArrowUpRight size={16} aria-hidden="true" /></Link></div></div><div className="home-hero-visual home-reveal" aria-hidden="true"><div className="home-hero-earth"><Image src="/media/home/nasa-blue-marble-alpha.webp" alt="" width={1600} height={1600} sizes="(max-width: 768px) 92vw, (max-width: 1200px) 58vw, 720px" priority /><span className="home-orbit home-orbit-one" /><span className="home-orbit home-orbit-two" /></div></div><ol className="home-hero-signals" aria-label="Current climate signals"><HeroSignal label="Atmospheric CO₂" value={currentCO2 ? `${currentCO2.value.toFixed(2)} ppm` : "Unavailable"} detail={currentCO2 ? formatClimateDate(currentCO2.observed_at) : "NOAA source unavailable"} type="estimate" /><HeroSignal label="ENSO state" value={enso?.status.alert_status ?? "Unavailable"} detail={enso ? `Issued ${formatClimateDate(enso.status.issued_at)}` : "NOAA analysis unavailable"} type="analysis" /><HeroSignal label="Temperature" value={temperature?.latest_anomaly ? `${formatSigned(temperature.latest_anomaly.value, 3)} °C` : "Unavailable"} detail={temperature?.latest_anomaly?.period ?? "NOAA analysis unavailable"} type="analysis" /><HeroSignal label="Seasonal outlook" value={outlook?.forecast_period.label ?? "Unavailable"} detail={outlook ? `Issued ${formatClimateDate(outlook.issue.issue_date)}` : "WMO forecast unavailable"} type="forecast" /></ol></div></section>
    <section id="signals" className="home-section home-signals"><div className="home-shell"><header className="home-section-heading home-reveal"><p className="home-kicker">01 · Live climate signals</p><h2>Different instruments. Different clocks. <em>One connected system.</em></h2><p>Each signal answers a distinct question. Follow its source for the full context and method.</p></header><div className="home-signal-grid"><article className="home-signal-card home-reveal"><DataTypeBadge type="estimate" /><h3>Carbon in the air</h3>{currentCO2 && co2?.series.length ? <><strong>{currentCO2.value.toFixed(2)} <small>ppm</small></strong><p>Atmospheric concentration is not the same measurement as annual emissions.</p><SeriesPlot points={co2.series} tone="carbon" label="Recent atmospheric carbon dioxide series" summary={`Observed ${formatClimateDate(currentCO2.observed_at)}.`} /><SourceBadge source={co2.source} compact /></> : <DataUnavailable label="Atmospheric CO₂" />}</article><article className="home-signal-card home-reveal"><DataTypeBadge type="analysis" /><h3>Global temperature</h3>{temperature?.latest_anomaly && temperature.historical_series.length ? <><strong>{formatSigned(temperature.latest_anomaly.value, 3)}<small> °C</small></strong><p>Measured against {temperature.baseline}, not Earth&apos;s absolute temperature.</p><SeriesPlot points={temperature.historical_series} tone="warm" label="Global temperature anomaly series" summary={temperature.latest_anomaly.period} /><SourceBadge source={temperature.source} compact /></> : <DataUnavailable label="Global temperature" />}</article><article className="home-signal-card home-reveal"><DataTypeBadge type="analysis" /><h3>Ocean heat</h3>{overview ? <><strong className="home-word-value">{overview.ocean.headline}</strong><p>{overview.ocean.summary}</p><div className="home-wave-graphic" aria-hidden="true"><span /><span /><span /></div><SourceBadge source={overview.ocean.source} compact /></> : <DataUnavailable label="Ocean context" />}</article><article className="home-signal-card home-reveal"><DataTypeBadge type="observation" /><h3>Pacific / ENSO</h3>{enso ? <><strong>{currentNino ? `${formatSigned(currentNino.value)}°C` : "Unavailable"}</strong><p>{enso.status.headline}</p>{enso.observations.nino34_series.length ? <SeriesPlot points={enso.observations.nino34_series} tone="cool" label="Niño 3.4 anomaly series" summary={currentNino?.period ?? "Current observation unavailable."} /> : null}<SourceBadge source={enso.observations.source} compact /></> : <DataUnavailable label="ENSO intelligence" />}</article></div></div></section>
    <section className="home-section home-pacific"><div className="home-shell home-pacific-grid"><div className="home-pacific-art home-reveal" aria-hidden="true"><div className="home-pacific-globe"><span /><span /><span /></div></div><div className="home-reveal"><p className="home-kicker">02 · Ocean + Pacific story</p><h2>The Pacific changes the rhythm, not the rules.</h2><p className="home-lead">Oceans store and redistribute heat. ENSO is a recurring ocean–atmosphere pattern that can shift the odds of conditions around the world from season to season.</p>{enso ? <div className="home-enso-evidence"><div><DataTypeBadge type="observation" /><strong>{currentNino ? `${formatSigned(currentNino.value)} °C` : "Unavailable"}</strong><p>Niño 3.4 · {currentNino?.period ?? "No current observation"}</p><DataFreshness freshness={enso.observation_freshness} /></div><div><DataTypeBadge type="analysis" /><strong>{enso.status.alert_status}</strong><p>{enso.status.summary}</p></div><div><DataTypeBadge type="forecast" /><strong>{enso.outlook.wmo.headline}</strong><p>{enso.outlook.wmo.summary}</p></div></div> : <DataUnavailable label="Pacific intelligence" />}<Link className="home-text-link" href="/climate-now/enso">Understand the Pacific signal <ArrowUpRight size={15} aria-hidden="true" /></Link></div></div></section>
    <section className="home-section home-watch"><div className="home-shell home-watch-grid"><div className="home-reveal"><p className="home-kicker">03 · What we&apos;re watching</p><h2>Forecasts describe shifts in probability.</h2><p className="home-lead">Seasonal outlooks summarize broad conditions over months. They are not daily weather predictions for a particular place.</p>{outlook ? <div className="home-outlook-card"><DataTypeBadge type="forecast" /><h3>{outlook.forecast_period.label}</h3><p>Issued {formatClimateDate(outlook.issue.issue_date)} · baseline {outlook.baseline}</p><div><span><Wind aria-hidden="true" /> ENSO</span><strong>{humanize(outlook.oceanic_drivers.enso.phase)}</strong><small>{outlook.oceanic_drivers.enso.status}</small></div><div><span><ThermometerSun aria-hidden="true" /> Temperature</span><strong>{outlook.temperature.headline}</strong><small>{outlook.temperature.tendencies[0] ? formatProbability(outlook.temperature.tendencies[0].probability, outlook.temperature.tendencies[0].qualifier) : "No probability supplied"}</small></div><div><span><CloudRain aria-hidden="true" /> Precipitation</span><strong>{outlook.precipitation.headline}</strong></div><SourceBadge source={outlook.sources[0]} compact /></div> : <DataUnavailable label="WMO seasonal outlook" />}</div><div className="home-arctic-card home-reveal"><Image src="/media/home/nasa-arctic-mosaic.webp" alt="Satellite mosaic looking down over the Arctic with sea ice, cloud systems, and northern landmasses." width={1800} height={1200} sizes="(max-width: 900px) 100vw, 48vw" loading="lazy" /><div><p className="home-kicker">Polar context</p>{overview ? <><h3>{overview.sea_ice.arctic.headline}</h3><p>{overview.sea_ice.arctic.summary}</p><p><Snowflake aria-hidden="true" /> Antarctic · {overview.sea_ice.antarctic.headline}</p><SourceBadge source={overview.latest_bulletin.source} compact /></> : <DataUnavailable label="Sea-ice analysis" />}</div></div></div></section>
    <section className="home-section home-events"><div className="home-shell"><header className="home-section-heading home-reveal"><p className="home-kicker">04 · Earth events now</p><h2>Location is context. <em>Detection is not attribution.</em></h2><p>Recent event detection, mapped from reported NASA EONET geometry.</p></header>{events ? <><div className="home-event-map home-reveal" aria-label="World map with recent NASA Earth event locations"><svg viewBox="0 0 100 50" role="img" aria-label="Simplified world projection using reported event coordinates"><path d="M3 14 14 8l13 3 6 9-6 9-15-2-9-6zm31-9 14-3 8 7-4 10-13 1-7-7zm26 8 11-6 15 5 9 9-7 12-21 2-9-10zm-5 22 10 1 5 8-10 3-6-7z" /><path d="M5 39h90M10 44h80M25 2v46M50 2v46M75 2v46" className="home-map-grid" />{events.events.slice(0,5).map((event) => { const point = eventPoint(event); return point ? <circle key={event.id} cx={point.x} cy={point.y / 2} r="1.2"><title>{event.title}</title></circle> : null; })}</svg><span>Reported locations · simplified projection</span></div><ol className="home-event-list">{events.events.slice(0, 5).map((event) => <EventCard event={event} key={event.id} />)}</ol><p className="home-event-disclaimer">{events.attribution_disclaimer}</p><SourceBadge source={events.source} compact /></> : <DataUnavailable label="NASA Earth Events" detail="No synthetic events have been substituted." />}<Link className="home-text-link" href="/events">Explore all events <ArrowUpRight size={15} aria-hidden="true" /></Link></div></section>
  </>;
}
