"""create climate and user actions"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20260904_0003"; down_revision="20260904_0002"; branch_labels=None; depends_on=None
def upgrade():
 op.create_table("climate_actions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("title",sa.String(160),nullable=False),sa.Column("slug",sa.String(180),nullable=False,unique=True),sa.Column("category",sa.String(20),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("why_it_matters",sa.Text()),sa.Column("difficulty",sa.String(10),nullable=False),sa.Column("impact_level",sa.String(10),nullable=False),sa.Column("estimated_co2e_kg",sa.Numeric(8,2)),sa.Column("xp_reward",sa.Integer(),nullable=False),sa.Column("recommendation_tags",postgresql.JSONB(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False)); op.create_index("ix_climate_actions_category","climate_actions",["category"])
 op.create_table("user_actions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id"),nullable=False),sa.Column("action_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("climate_actions.id"),nullable=False),sa.Column("status",sa.String(12),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("xp_awarded",sa.Integer(),nullable=False,server_default="0"),sa.Column("estimated_co2e_kg_awarded",sa.Numeric(8,2),nullable=False,server_default="0"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False)); op.create_index("ix_user_actions_user_created","user_actions",["user_id","created_at"]); op.create_index("ix_user_actions_user_status","user_actions",["user_id","status"])
def downgrade():
 op.drop_table("user_actions"); op.drop_table("climate_actions")
