"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import { AuthNav } from "@/components/layout/auth-nav";

type DashboardData = { name: string; xp: number; current_streak: number; climate_score: number | null; category_scores: Record<string, number> | null; lowest_category: string | null; estimated_co2e_avoided: string; recent_activity: { title: string; completed_at: string; xp_awarded: number }[]; recommendations: { id: string; title: string; difficulty: string; xp_reward: number; recommendation_reason: string }[] };

export default function Dashboard() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { apiFetch<DashboardData>("/dashboard").then(setDashboard).catch((requestError: Error) => setError(requestError.message)); }, []);

  if (error) return <main className="min-h-screen bg-[#071A17] p-8 text-[#F4FFF9]"><div className="mx-auto max-w-xl rounded-2xl border border-white/10 bg-[#0E2722] p-6"><h1 className="text-2xl font-semibold">Sign in to view your dashboard.</h1><p className="mt-3 text-[#A5BBB2]">Your progress is safely stored in your EcoPulse account.</p><Link className="mt-5 inline-block rounded-lg bg-[#5EE89A] px-4 py-2 font-semibold text-[#071A17]" href="/login">Sign In</Link></div></main>;
  if (!dashboard) return <main className="min-h-screen bg-[#071A17] p-8 text-[#F4FFF9]">Loading your progress…</main>;

  const metrics = [["Climate Action Score", dashboard.climate_score === null ? "—" : `${dashboard.climate_score}/100`], ["Total XP", dashboard.xp], ["Current Streak", `${dashboard.current_streak} days`], ["Estimated CO2e Avoided", `${dashboard.estimated_co2e_avoided} kg`]];
  return <main className="min-h-screen bg-[#071A17] p-5 text-[#F4FFF9]"><div className="mx-auto max-w-6xl"><AuthNav /><div className="py-10"><p className="text-[#5EE89A]">ECO PULSE</p><h1 className="mt-2 text-4xl font-bold">Your climate action progress, {dashboard.name}.</h1><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <section key={String(label)} className="rounded-2xl border border-white/10 bg-[#0E2722] p-5"><p className="text-[#A5BBB2]">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></section>)}</div>{!dashboard.category_scores ? <section className="mt-8 rounded-2xl bg-[#15332C] p-6"><h2 className="text-2xl font-semibold">Start with your assessment</h2><p className="mt-2 text-[#A5BBB2]">Your first Climate Action Score will unlock personalized next steps.</p><Link className="mt-4 inline-block rounded bg-[#5EE89A] px-4 py-2 text-[#071A17]" href="/assessment">Take assessment</Link></section> : <><section className="mt-8 rounded-2xl bg-[#0E2722] p-6"><h2 className="text-2xl font-semibold">Category scores</h2>{Object.entries(dashboard.category_scores).map(([category, score]) => <div className="mt-4" key={category}><div className="flex justify-between capitalize"><span>{category}{category === dashboard.lowest_category ? " · opportunity" : ""}</span><span>{score}/100</span></div><div className="mt-1 h-3 rounded bg-white/10"><div className="h-3 rounded bg-[#5EE89A]" style={{ width: `${score}%` }} /></div></div>)}</section><section className="mt-8"><h2 className="text-2xl font-semibold">Recommended next actions</h2><div className="mt-3 grid gap-4 md:grid-cols-3">{dashboard.recommendations.map((item) => <article key={item.id} className="rounded-xl bg-[#15332C] p-5"><h3 className="font-semibold">{item.title}</h3><p className="mt-2 text-sm text-[#A5BBB2]">{item.recommendation_reason}</p><p className="mt-3 text-sm">{item.difficulty} · {item.xp_reward} XP</p></article>)}</div><Link className="mt-4 inline-block text-[#62D9FF]" href="/actions">Manage actions →</Link></section></>}<section className="mt-8"><h2 className="text-2xl font-semibold">Recent activity</h2>{dashboard.recent_activity.length ? dashboard.recent_activity.map((item) => <p className="mt-3 rounded bg-[#0E2722] p-4" key={item.completed_at}>{item.title} · +{item.xp_awarded} XP</p>) : <p className="mt-3 text-[#A5BBB2]">Your first action is waiting. <Link className="text-[#62D9FF]" href="/actions">Explore actions</Link></p>}</section></div></div></main>;
}
